import Footer from "@/components/layout/footer";
import "./globals.css";

import Header from '@/components/layout/header';

export const metadata= {
  title: "Supreme Group",
  description: "Generated by create next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}